### ISSUE TITLE
Prepared statements and unknown type

### ISSUE THREAD

**Issue by ruslantalpa** [nikita-volkov/hasql-postgres#27]
In postgresql i can do something like
```
PREPARE clients_stmp (unknown) AS SELECT * FROM clients WHERE id = $1;
EXECUTE clients_stmp('1');
```

We talked about this in #23 (sorry for asking the same question twice) and at the time, the conclusion was that the binary protocol does not support "unknown" but it seems that prepared statements somehow work with it.

My goal here is sending (through hasql) prepared statements rather then queries.
I thought this might work (probably tried it before) but it didn't
```
rows <- H.tx Nothing $ H.listEx $ [H.stmt|SELECT * FROM clients WHERE id = ?::unknown|] ("1"::Text)
```
got back

```
ERROR,XX000,"failed to find conversion function from unknown to integer",,,,,,"SELECT * FROM clients WHERE id = $1::unknown"
```
which is a bit strange since the same cast worked before with PREPARE/EXECUTE
What am i missing?

**Comment by ruslantalpa** [comment]
Ha! Progress!
This works
```
rows <- H.tx Nothing $ H.listEx $ [H.stmt|SELECT * FROM clients WHERE id = ?::integer|] ("1"::Text)
```

**Comment by nikita-volkov** [comment]
The problem was in your statement. The casting in the SQL (`::unknown`) has nothing to do with Hasql, it only affects Postgres. It tells Postgres to downcast whatever the type there was to the type `unknown`, which is evidently not what you want, since it is not the type of the `id` column, which you are comparing the value with. IOW, you were comparing values of different types, thus introducing a type error. The error you got was the Postgres' way of explaining that.
