### ISSUE TITLE
Mapping Postgres Value

### ISSUE THREAD

**Issue by agrafix** [nikita-volkov/hasql-postgres#5]
A `Mapping Postgres Value` would be very useful to support the Postgresql json/jsonb types. Maybe define a newtype Wrapper to distinguish between the two types?

**Comment by nikita-volkov** [comment]
Implemented in 0.10.2

**Comment by agrafix** [comment]
Wow, this is great news! Thank you! 
If i see it correctly you are using the postgres json type. Postgresql 9.4 now has a faster jsonb type - would it be possible to support that, too? Maybe via a newtype wrapper around `Value`?

**Comment by nikita-volkov** [comment]
It would be possible. The implementation should be trickier, since JSONB seems to be transferred in the binary format unlike JSON, so this would involve updating the "postgresql-binary" library as well. 

I'm definitely not going to jump on this one any time soon since I don't plan to be using this type, so we'll need a contribution. As always I'll gladly help out and direct the one daring to accept this challenge.

**Comment by nikita-volkov** [comment]
Hey man! :) It's implemented in the latest "hasql" release.

**Comment by agrafix** [comment]
Very cool! Looking forward to using this! :-)
